---
# configure_and_start_teleport/tasks/main.yml

- name: "Create directory {{ teleport_data_directory }}"
  ansible.builtin.file:
    path: "{{ teleport_data_directory }}"
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0750'

- name: 'Create the teleport.yaml'
  ansible.builtin.template:
    src: 'teleport.yaml.j2'
    dest: '/etc/teleport.yaml'
    owner: 'root'
    group: 'root'
    mode: '0600'
  notify:
    - 'Restart the teleport service'

- name: 'Start the teleport service'
  ansible.builtin.service:
    name: "{{ systemd_unit_name }}"
    state: 'started'
  when:
    - 'start_the_service | bool'

- name: 'Enable the teleport service'
  ansible.builtin.service:
    name: "{{ systemd_unit_name }}"
    enabled: 'true'
  when:
    - 'enable_the_service | bool'
