---
# configure_and_start_teleport/handlers/main.yml

- name: 'Trigger systemctl daemon-reload'
  ansible.builtin.systemd:
    daemon_reload: 'yes'

- name: 'Restart the teleport service'
  ansible.builtin.service:
    name: "{{ systemd_unit_name }}"
    state: 'restarted'
